# Generated by Django 3.0.7 on 2020-06-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('dateCreated', models.DateTimeField()),
                ('dateOfBirth', models.DateField()),
            ],
        ),
    ]
